<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class BankController extends Controller
{

    public function index(Request $request)
    {
        $all_usa_banks = [
            'AMERIS BANK',
            'BANCO POPULAR',
            'BANCORP SOUTH',
            'BANCORPSOUTH',
            'BANCORPSOUTH BANK',
            'BANK OF AMERICA',
            'BANK OF COMMERCE',
            'BANK OF HOPE',
            'BANK OF NEW YORK MELLON',
            'BANK OF NORTH CAROLINA',
            'BANK OF THE OZARKS',
            'BANK OF THE WEST',
            'BANKPLUS',
            'BANNER BANK',
            'BEAR STATE BANK',
            'BERKSHIRE BANK',
            'BMO HARRIS BANK',
            'BRANCH BANKING & TRUST COMPANY',
            'BUSEY BANK',
            'BYLINE BANK',
            'CADENCE BANK',
            'CAMDEN NATIONAL BANK',
            'CAPITAL BANK CORPORATION',
            'CAPITAL BANK',
            'CAPITAL CITY BANK',
            'CAPITAL ONE',
            'CATHAY BANK',
            'CENTENNIAL BANK',
            'CENTRAL BANK',
            'CHEMICAL BANK',
            'CITIBANK',
            'CITIBANK WEST',
            'CITIZENS BANK',
            'CITIZENS BUSINESS BANK',
            'CITIZENS NATIONAL BANK',
            'CITIZENS STATE BANK',
            'CITY NATIONAL BANK',
            'COLUMBIA STATE BANK',
            'COMERICA BANK',
            'COMMERCE BANK',
            'COMMERCIAL BANK',
            'COMMUNITY BANK',
            'COMMUNITY FIRST BANK',
            'COMMUNITY NATIONAL BANK',
            'COMMUNITY STATE BANK',
            'COMPASS BANK',
            'CORNERSTONE BANK',
            'CREDIT UNION OF SOUTHERN CALIFORNIA',
            'EAST WEST BANK',
            'EASTERN BANK',
            'FARMERS & MERCHANTS BANK',
            'FARMERS BANK',
            'FARMERS STATE BANK',
            'FEDERAL RESERVE BANK',
            'FIDELITY BANK',
            'FIFTH THIRD BANK',
            'FINANCIAL PARTNERS CREDIT UNION',
            'FIRST BANK',
            'FIRST BANK & TRUST',
            'FIRST CITIZENS BANK & TRUST COMPANY',
            'FIRST COMMUNITY BANK',
            'FIRST FIDELITY BANK',
            'FIRST FINANCIAL BANK',
            'FIRST MERCHANTS BANK',
            'FIRST MIDWEST BANK',
            'FIRST NATIONAL BANK',
            'FIRST NATIONAL BANK OF OMAHA',
            'FIRST NATIONAL BANK OF PENNSYLVANIA',
            'FIRST SAVINGS BANK',
            'FIRST SECURITY BANK',
            'FIRST STATE BANK',
            'FIRST TENNESSEE BANK',
            'FIRSTBANK',
            'FRANDSEN BANK & TRUST',
            'GERMAN AMERICAN BANCORP',
            'GLACIER BANK',
            'GOLDMAN SACHS BANK USA',
            'GRANDPOINT BANK',
            'GREAT LAKES CREDIT UNION',
            'GREAT SOUTHERN BANK',
            'GREAT WESTERN BANK',
            'HERITAGE BANK',
            'HORIZON CREDIT UNION',
            'HSBC BANK',
            'HUNTINGTON NATIONAL BANK',
            'IBERIABANK',
            'INDEPENDENT BANK',
            'INTERBANK',
            'INTERNATIONAL BANK OF COMMERCE',
            'JPMORGAN CHASE',
            'KEY BANK',
            'KEYBANK',
            'LIBERTY BANK',
            'M & T BANK',
            'M B FINANCIAL BANK',
            'MAINSOURCE BANK',
            'MUFG UNION BANK',
            'NBH BANK',
            'NEW YORK COMMUNITY BANK',
            'PACIFIC WESTERN BANK',
            'PARK NATIONAL BANK',
            'PENTAGON FEDERAL CREDIT UNION',
            'PEOPLES BANK',
            'PEOPLES STATE BANK',
            'PINNACLE BANK',
            'PIONEER BANK, SSB',
            'PNC BANK INC. - BALTIMORE',
            'PNC BANK',
            'PROSPERITY BANK',
            'REGIONS BANK',
            'RENASANT BANK',
            'S & T BANK',
            'SANTANDER BANK',
            'SECURITY BANK',
            'SECURITY STATE BANK',
            'SELF-HELP CREDIT UNION',
            'SIMMONS FIRST NATIONAL BANK',
            'SIMMONS FIRST NATL BK',
            'SOUTH STATE BANK',
            'STATE BANK AND TRUST COMPANY',
            'STERLING NATIONAL BANK',
            'STONEGATE BANK',
            'TD BANK',
            'THE HUNTINGTON NATIONAL BANK',
            'THE PEOPLES BANK',
            'TRUSTMARK NATIONAL BANK',
            'UMB',
            'UMPQUA BANK',
            'UNIFY FINANCIAL FEDERAL CREDIT UNION',
            'UNION BANK & TRUST',
            'UNION STATE BANK',
            'UNITED BANK',
            'UNITED BANK & CAPITAL TRUST COMPANY',
            'UNITED COMMUNITY BANK',
            'US BANK',
            'USALLIANCE FEDERAL CREDIT UNION',
            'VALLEY NATIONAL BANK',
            'WEBSTER BANK',
            'WELLS FARGO BANK',
            'WESBANCO BANK INC',
            'WHITNEY BANK',
            'XENITH BANK',
        ];
    }
}
